baseurl = "https://hasifjalil.xyz"
title = "DevOps with love"
theme = "hugo-coder-forked"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "hasifjalil"
enableGitInfo = true
enableRobotsTXT = true

# Hugo settings
[sitemap]
changefreq = 'weekly'
filename = 'sitemap.xml'
priority = 0.5

[params]
author = "Hasif Jalil"
info = ["Full Stack DevOps and Magician"]
description = "Hasif Jalil's personal page"
keywords = "blog,businesscard,personal,devops,hasifabduljalil,hasif,jalil"
avatarurl = "https://avatars.githubusercontent.com/u/153401666?s=400&u=8ddfe67f3e34a082e5a7a854fac59f6db36ac49a&v=4"

faviconSVG = "/img/favicon.svg"
favicon_32 = "/img/favicon.png"

since = 2010
enableTwemoji = true
colorScheme = "auto"
hidecolorschemetoggle = false
# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/hasifabduljalil/hasifjalil.xyz/tree/"
powered_by = true
# Series see also post count
maxSeeAlsoItems = 5

[taxonomies]
#tag = "tags"
#author = "authors"

# Social links
[[params.social]]
name = "Github"
icon = "fa fa-github fa-2x"
weight = 1
url = "https://github.com/hasifabduljalil/"
target = "_blank"
[[params.social]]
name = "Gitlab"
icon = "fa fa-gitlab fa-2x"
weight = 2
url = "https://gitlab.com/hasifabduljalil"
target = "_blank"
[[params.social]]
name = "Instagram"
icon = "fa fa-instagram fa-2x"
weight = 3
url = "https://www.instagram.com/hasifjalil/"
target = "_blank"
[[params.social]]
name = "Linkedin"
icon = "fa fa-linkedin fa-2x"
weight = 5
url = "https://www.linkedin.com/in/hasifjalil/"
target = "_blank"
[[params.social]]
name = "k@kazakov.xyz"
icon = "fa fa-envelope fa-2x"
weight = 6
url = "mailto:hasifabduljalil@gmail.com"
target = "_blank"

# Menu links
[[languages.en.menu.main]]
name = "Home"
weight = 1
url  = "/"
[[languages.en.menu.main]]
name = "About"
weight = 2
url = "about/"


